/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package fr.dlesaout.openfoodfactswrapper.controller;

import fr.dlesaout.openfoodfactswrapper.model.ProductList;
import fr.dlesaout.openfoodfactswrapper.model.ProductResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;


@Tag(name = "products", description = "the products API")
public interface ProductsApi {

    @Operation(summary = "Info for a specific product", operationId = "fetchProductByCode",
            responses = {
                    @ApiResponse(responseCode = "200", description = "Expected response to a valid request",
                            content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE,
                                    schema = @Schema(implementation = ProductResponse.class))),
                    @ApiResponse(responseCode = "default", description = "unexpected error",
                            content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE,
                                    schema = @Schema(implementation = Error.class)))
            })
    @GetMapping(value = "/products/{code}", produces = MediaType.APPLICATION_JSON_VALUE)
    default ResponseEntity<ProductResponse> fetchProductByCode(@PathVariable("code") String code) {
        return ResponseEntity.status(HttpStatus.NOT_IMPLEMENTED).build();
    }

    @Operation(summary = "List of products", operationId = "fetchProducts",
            responses = {
                    @ApiResponse(responseCode = "200", description = "Expected response to a valid request",
                            content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE,
                                    array = @ArraySchema(schema = @Schema(implementation = ProductList.class)))),
                    @ApiResponse(responseCode = "default", description = "unexpected error",
                            content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE,
                                    schema = @Schema(implementation = Error.class)))
            })
    @GetMapping(value = "/products/search", produces = MediaType.APPLICATION_JSON_VALUE)
    default ResponseEntity<ProductList> fetchProducts(
            @RequestParam(value = "nutriscore", required = false) String nutriscore,
            @RequestParam(value = "category", required = false) String category,
            @RequestParam(value = "brand", required = false) String brand,
            @RequestParam(value = "fields", required = false) List<String> fields,
            @RequestParam(value = "page", required = false) Integer page) {
        return ResponseEntity.status(HttpStatus.NOT_IMPLEMENTED).build();
    }
}
